# Generated by Django 3.1.2 on 2020-10-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pyme_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raz_soc', models.TextField()),
                ('giro', models.TextField()),
                ('l_agua', models.FloatField()),
                ('coste_agua', models.FloatField()),
                ('kW', models.FloatField()),
                ('coste_luz', models.FloatField()),
                ('l_gas', models.IntegerField()),
                ('coste_gas', models.FloatField()),
            ],
        ),
    ]
